apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: sample-app-config
    envs:
      - config.env

patches:
  - target:
      kind: Deployment
    path: patch.yaml